---
- name: Create Marathon conf directory
  file: path=/etc/marathon/conf state=directory

- name: Set requied --master option
  lineinfile: line={{ mesos_zookeeper_masters }} dest=/etc/marathon/conf/master create=yes
  notify:
    - Restart marathon

- name: Remove optional --artifact_store option
  file: path=/etc/marathon/conf/artifact_store state=absent
  when: artifact_store == ""
  notify:
    - Restart marathon

- name: Set optional --artifact_store option
  template: src=artifact_store.j2 dest=/etc/marathon/conf/artifact_store
  when: artifact_store != ""
  notify:
    - Restart marathon

- name: Remove optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=absent
  when: checkpoint == ""
  notify:
    - Restart marathon

- name: Set optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=touch
  when: checkpoint != ""
  notify:
    - Restart marathon

- name: Remove optional --zk option
  file: path=/etc/marathon/conf/zk state=absent
  when: marathon_zookeeper_state == ""
  notify:
    - Restart marathon

- name: Set optional --zk option
  template: src=zk.j2 dest=/etc/marathon/conf/zk
  when: marathon_zookeeper_state != ""
  notify:
    - Restart marathon

- name: Set --hostname option
  lineinfile: line={{ marathon_hostname }} dest=/etc/marathon/conf/hostname create=yes
  notify:
    - Restart marathon

- name: Set --http-port option
  lineinfile: line={{ marathon_port }} dest=/etc/marathon/conf/http_port create=yes
  notify:
    - Restart marathon
